### ISSUE TITLE
Github Code Colors - color swatch not always displaying

### ISSUE THREAD

**Issue by JackofSpades707** [Mottie/GitHub-userscripts#154]
![image](https://user-images.githubusercontent.com/17239750/122590088-ecc29d80-d015-11eb-9572-c4e1e8fcc231.png)
Works just fine for JS but not for CSS codeblocks

[Link](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-code-colors)

**Comment by JackofSpades707** [comment]
Did a quick test to showcase it in more depth.

<details>
<summary>Codeblock</summary>

```css
.style {
  ctx.fillStyle = 'gold';
  ctx.fillRect(0,0,75,75);
  ctx.fillStyle = '#6C0';
  ctx.fillRect(75,0,75,75);
  ctx.fillStyle = '#0FF';
  ctx.fillRect(0,75,75,75);
  ctx.fillStyle = 'hsl(12, 100%, 50%)';
  ctx.fillRect(75,75,75,75);
  ctx.fillStyle = 'rgba(255, 255, 255, 1)';
  background: #123456;
  color: rgb( 255,128,64);
  border-left: 1px hsla(65, 100%, 50%, 1) solid;
  border-right-color: maroon;
  box-shadow: 3px 3px hsl( 128, 30%, 50% );
  text-shadow: 2px 5px rgba(255, 0,  183,0.5);
}
```
</details>

<details>
<summary>Result</summary>

![image](https://user-images.githubusercontent.com/17239750/122596155-4e870580-d01e-11eb-8800-98da962e701f.png)

</details>
