### ISSUE TITLE
GitHub code folding - the last block does not get a folding arrow

### ISSUE THREAD

**Issue by sabi0** [Mottie/GitHub-userscripts#196]
I have some YAML files describing a bunch of instances for Kubernetes deployment.
And I noticed that all the instances are foldable except for the last one in a file:
![image](https://github.com/Mottie/GitHub-userscripts/assets/11509875/0ea448cf-0592-4964-8c0a-e246d841b495)

Here "prod2x" and "class-prod" blocks have the exact same layout. And the "class-prod" is the last one in the file.

```yaml
instances:
- name: prod2x:
   source:
    revision: deadbeef
- name: class-prod
  source:
    revision: cafebabe
```
