### ISSUE TITLE
Steamcommunity auto show spoiler content

### ISSUE THREAD

**Issue by Bluscream** [Mottie/GitHub-userscripts#50]
On steam community pages there are spoilers

```css
span.bb_spoiler {
  color: #000000;
  background-color: #000000;
  padding: 0px 8px;
}
```
i know it's not github related but it would still neat if you could give me a script which makes them automatically readable

Without hover:
![grafik](https://user-images.githubusercontent.com/3318223/42124944-3a65fdcc-7c5c-11e8-867a-b1002073a1e4.png)
With hover:
![grafik](https://user-images.githubusercontent.com/3318223/42124945-3ffafa62-7c5c-11e8-94c6-751e8a1ec5a0.png)
